apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne 
  storage:
    type: memory 
    options: 
      memory: 
        max-traces: 1000000
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - mesh-jaeger.cluster.prageethw.com
  agent:
    strategy: DaemonSet
